name: Docker Push

on:
  push:
    tags:
      - v*
    paths:
      - apps/**/*.{ts,html,scss,css}
      - libs/**/*.{ts}

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      CHATTR_VERSION: '1.0.3'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Connect your workspace on nx.app and uncomment this to enable task distribution.
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "build" targets have been requested
      # - run: yarn nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="build"

      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json
      - run: npm install -g pnpm
      - run: pnpm i --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      # - run: pnpm nx-cloud record -- nx format:check
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - run: pnpm nx affected -t docker-push --head=$NX_HEAD --base=$NX_BASE
